spring.application.name=dataset-api


spring.datasource.url=jdbc:postgresql://localhost:5432/datamarket
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# JPA Config
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080

# JWT config
jwt.secret=mysupersecretkeymysupersecretkey123456 
jwt.expiration=3600000  
#OAuth2 config
spring.security.oauth2.client.registration.google.client-id=624073973217-6cm9s3qttvup2c94sp9r7vppdake5q7j.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

#Cloundinary Config
cloudinary.cloud_name=dofuoy88z
cloudinary.api_key=921526637348378
cloudinary.api_secret=UUnGLuumsX82bMgHBpojb_hW_7A
##ConfigEndpoint
api.public=/api/public
api.common=/api

frontEndUrl = http://localhost:3000

google.drive.credentials.path=src/main/resources/credentials.json
google.drive.folder.id=1ldr-7SLPphudLfN9El5Pu5ucLBUKaUS0


# VNPAY config
vnpay.tmn-code=HKN6O7QC
vnpay.hash-secret=Z3VQSTV63DZAO5UTXCJHS97HNGLLJSEJ
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:8080/api/payment/return
# vnpay.ipn-url
#EVisiondataset@gmail.com
#EVision@123