spring.application.name=dataset-api

spring.datasource.url=jdbc:postgresql://localhost:5432/datamarket
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA Config
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080

# JWT config
jwt.secret=mysupersecretkeymysupersecretkey123456 
jwt.expiration=3600000  
#OAuth2 config
spring.security.oauth2.client.registration.google.client-id=624073973217-6cm9s3qttvup2c94sp9r7vppdake5q7j.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub