# Spring Boot Application
spring.application.name=dataset-api

# Database Config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA Config
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.type.descriptor.sql=TRACE

# Log SQL sinh ra

#logging.level.org.hibernate.SQL=DEBUG

# Log parameter ???c bind v�o SQL
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Server Config
server.port=8080

# JWT Config
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

# OAuth2 Google Config
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
# Cloudinary Config
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# API Endpoint Config
api.public=/api/public
api.common=/api
frontEndUrl=http://localhost:3000

# VNPAY Config
vnpay.tmn-code=${VNPAY_TMN_CODE}
vnpay.hash-secret=${VNPAY_HASH_SECRET}
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url: https://data-market-ev.vercel.app/payment-result

# AWS Config
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region.static=ap-southeast-2
aws.bucket.name=${AWS_BUCKET_NAME}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8


spring.mail.properties.mail.smtp.starttls.required=true

# Very important: timeouts (ms) — tránh treo request quá lâu
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# Bật debug
spring.mail.properties.mail.debug=true


spring.ai.google.genai.project-id=gen-lang-client-0287450096
spring.ai.google.genai.location=us-central1
spring.ai.google.genai.api-key=${GEMINI_API_KEY}


app.frontend-url=https://data-market-ev.vercel.app/login
app.backend-url=http://localhost:8080

