spring.application.name=demo
# MySQL JDBC configuration
# MSSQL JDBC configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=SWF;encrypt=false
spring.datasource.username=sa
spring.datasource.password=12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

